---
title: "Publications"
---
<br>

<br>

### 2021

* Horizontal stratification in the city: Field of study, gentrification, and the social topography of Los Angeles. Los Angeles, CA: UCLA. [Link](https://www.proquest.com/docview/2546904619?pq-origsite=gscholar&fromopenview=true)

### 2020

* Schools should consider multigenerational families in reopening plans. (*with Cecilia Rios-Aguilar*). Palo Alto, CA: PACE. [Link](https://edpolicyinca.org/newsroom/schools-should-consider-multigenerational-households-reopening-plans)

* College students' support for wealth redistribution: Evidence from a national survey. *Journal of College & Character*. [Link](https://www.tandfonline.com/doi/pdf/10.1080/2194587X.2020.1781658?casa_token=9K40I6TewGAAAAAA:hJcEPIBZzpbQHaM_2CWeGv7rbfHZKNsvfdfJj5d_n9WCDo2du7pCU0QVpqvgR2mMkXK5Bc7Lkh01gg)


### 2019

* Health conditions among unsheltered adults in the U.S. (*with Janey Rountree and Nathan Hess*). Los Angeles, CA: California Policy Lab. [Link](https://www.capolicylab.org/health-conditions-among-unsheltered-adults-in-the-u-s/)



* College affordability in every corner of California: Perspectives from the 2019
PACE/USC Rossier Poll. (*with Cecilia Rios-Aguilar, Michal Kurlaender, and Teresita Martinez*). Palo Alto, CA: Policy Analysis for California Education. [Link](https://edpolicyinca.org/sites/default/files/PB_Rios-Aguilar_June2019.pdf)


* Higher education hotspots: Using local indicators of spatial association. *New Directions for Institutional Research*, 2018 (180), 59-68. [Link](https://onlinelibrary.wiley.com/doi/abs/10.1002/ir.20286)


### 2018 
* Institutional effects of higher education acquisitions: The Case of Texas A\&M School of Law. *AERA Open*, 4(4), 1-11. [Link](https://journals.sagepub.com/doi/10.1177/2332858418816092)

* Text me: The promise of strategic nudging to increase student awareness and access to financial aid. (*with Cecilia Rios-Aguilar, Paul Martinez, Devon Graves, Diana Lopez, and Regina Deil-Amen*). Davis, CA: Wheelhouse: The Center for Community College Leadership and Research. [Link](https://education.ucdavis.edu/sites/main/files/ucdavis_wheelhouse_research_brief_vol3no4_online.pdf)

* Marijuana laws: Relationship between state policy and drug and alcohol violations in on-campus housing. *Journal of College and University Student Housing*, 44(3), 96-110. [Link](http://www.nxtbook.com/nxtbooks/acuho/journal_vol44no3/index.php#/98)

* New California cannabis law may trip up college students. *San Francisco Chronicle*, January 1. [Link](https://www.sfchronicle.com/opinion/openforum/article/California-cannabis-law-may-trip-up-college-12462902.php)

### 2017

* Habitus, doxa, and saga: Applications of Bourdieu’s theory of practice to organizational history. *Management & Organizational History*, 12(2),163-173. [Link](https://www.tandfonline.com/doi/abs/10.1080/17449359.2017.1329091?journalCode=rmor20)

* The irrationality of college choice. *Inside Higher Ed*, March 22. [Link](https://www.insidehighered.com/views/2017/03/22/irrationality-college-choice-essay)